// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eElection.Data;

#nullable disable

namespace eElection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250319014755_AddNewTableElectionType")]
    partial class AddNewTableElectionType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eElection.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("VoterId")
                        .IsUnique()
                        .HasFilter("[VoterId] IS NOT NULL");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            AccountId = 5,
                            CreatedAt = new DateTime(2025, 3, 8, 3, 49, 50, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmationToken = "9f88c35b-f85f-4add-9023-05fdf5411e24",
                            IsEmailConfirmed = false,
                            Password = "AQAAAAIAAYagAAAAEBsg6iR+zJKFGlZtsAI2bTE68Ji5i2iemqzz1YktMbkp5EgvTbOTSELClp3e8Gq3kg==",
                            Username = "admin",
                            VoterId = 4
                        },
                        new
                        {
                            AccountId = 7,
                            CreatedAt = new DateTime(2025, 3, 10, 7, 33, 20, 0, DateTimeKind.Unspecified),
                            Email = "lemuelcueto21@gmail.com",
                            EmailConfirmationToken = "c8919e1a-2110-4757-926f-daa3035cacb5",
                            IsEmailConfirmed = true,
                            Password = "AQAAAAIAAYagAAAAEB64volyPMvo1GSwisFZZsYtvWpZngvA7soffvSSMuKuiobkLOwAY6Zgk9cldGj3aA==",
                            Username = "lemuel",
                            VoterId = 6
                        },
                        new
                        {
                            AccountId = 9,
                            CreatedAt = new DateTime(2025, 3, 14, 0, 58, 1, 0, DateTimeKind.Unspecified),
                            Email = "cueto.johnlemuel.j@gmail.com",
                            EmailConfirmationToken = "",
                            IsEmailConfirmed = true,
                            Password = "AQAAAAIAAYagAAAAEAkp4GQjt/Ey18RGW696gSkotd8CHsjy6Zv5VfuMSFDI435GMvEczn3zf9zadJP0Jw==",
                            Username = "Jandel Escalera",
                            VoterId = 22
                        },
                        new
                        {
                            AccountId = 10,
                            CreatedAt = new DateTime(2025, 3, 14, 0, 59, 45, 0, DateTimeKind.Unspecified),
                            Email = "johnlemuelcueto.olloka@gmail.com",
                            EmailConfirmationToken = "",
                            IsEmailConfirmed = true,
                            Password = "AQAAAAIAAYagAAAAEP5sSrBrZV03W+AbSn1NyMjVKQfqEY7xkUT9Rz/TRraD/x5CXa3TYlVToCKkFqqmwg==",
                            Username = "King Pacheco",
                            VoterId = 23
                        },
                        new
                        {
                            AccountId = 11,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 53, 21, 0, DateTimeKind.Unspecified),
                            Email = "deployhaha@gmail.com",
                            EmailConfirmationToken = "827c9562-71ba-4e14-b557-0d773b4e2a28",
                            IsEmailConfirmed = true,
                            Password = "AQAAAAIAAYagAAAAEPJM1uM6eC/RJz77uZFFNUoQ5f/1GuYY+g5wYi63JluogLt27u0UWEHWxmvXKC/9tw==",
                            Username = "Quinee",
                            VoterId = 24
                        },
                        new
                        {
                            AccountId = 12,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 54, 58, 0, DateTimeKind.Unspecified),
                            Email = "jandeleido@gmail.com",
                            EmailConfirmationToken = "22aee146-620f-416c-b814-884d8e29a4ef",
                            IsEmailConfirmed = true,
                            Password = "AQAAAAIAAYagAAAAELRRPNDnSUCikTQDkjqQ6gHq9OTEAIoxYz0/AH4M01n6+JFyKU/bgrDVM7aLjYKuIw==",
                            Username = "Claude",
                            VoterId = 25
                        });
                });

            modelBuilder.Entity("eElection.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AnnouncementId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = 2,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            Description = "Don't forget to vote on the upcoming election day!",
                            Status = "Published",
                            Title = "Election Day Reminder"
                        },
                        new
                        {
                            AnnouncementId = 3,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            Description = "Voter registration has been extended until next Friday.",
                            Status = "Published",
                            Title = "Registration Deadline Extended"
                        },
                        new
                        {
                            AnnouncementId = 4,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            Description = "Official election results will be announced this weekend.",
                            Status = "Scheduled",
                            Title = "Election Results Announcement"
                        });
                });

            modelBuilder.Entity("eElection.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PartyId");

                    b.HasIndex("PositionId");

                    b.HasIndex("VoterId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            CandidateId = 9,
                            Biography = "John Lemuel Cueto is a dedicated leader and public servant with a strong vision for a better and more progressive nation. Born and raised in [Location], he has been deeply committed to serving the people and advocating for meaningful change.\n\nJohn holds a degree in [Field of Study] from [University Name] and has extensive experience in [related profession or public service]. Over the years, he has led numerous initiatives focused on [key achievements such as economic development, social welfare programs, education reforms, or infrastructure projects].\n\nAs a candidate for President, John Lemuel Cueto aims to prioritize good governance, economic growth, quality education, accessible healthcare, and national security. He believes in transparency, accountability, and inclusive leadership, ensuring that every citizen has a voice in shaping the nation's future.\n\nWith a strong track record of leadership, integrity, and dedication, John Lemuel Cueto is ready to lead the country toward progress and prosperity.\n\nCampaign Slogan: \"Together, We Build a Stronger Nation!\"",
                            CreatedAt = new DateTime(2025, 3, 14, 0, 57, 5, 0, DateTimeKind.Unspecified),
                            ElectionId = 10,
                            PartyId = 2,
                            PositionId = 6,
                            VoterId = 6
                        },
                        new
                        {
                            CandidateId = 10,
                            Biography = "Jandel Escalera is a dedicated leader and public servant with a strong vision for a better and more progressive nation. Born and raised in [Location], he has been deeply committed to serving the people and advocating for meaningful change.\n\nJandel holds a degree in [Field of Study] from [University Name] and has extensive experience in [related profession or public service]. Over the years, he has led numerous initiatives focused on [key achievements such as economic development, social welfare programs, education reforms, or infrastructure projects].\n\nAs a candidate for President, Jandel Escalera aims to prioritize good governance, economic growth, quality education, accessible healthcare, and national security. He believes in transparency, accountability, and inclusive leadership, ensuring that every citizen has a voice in shaping the nation's future.\n\nWith a strong track record of leadership, integrity, and dedication, Jandel Escalera is ready to lead the country toward progress and prosperity.\n\nCampaign Slogan: \"Together, We Build a Stronger Nation!\"",
                            CreatedAt = new DateTime(2025, 3, 14, 2, 25, 54, 0, DateTimeKind.Unspecified),
                            ElectionId = 10,
                            PartyId = 6,
                            PositionId = 7,
                            VoterId = 22
                        },
                        new
                        {
                            CandidateId = 11,
                            Biography = "King Pacheco is a dedicated leader and public servant with a strong vision for a better and more progressive nation. Born and raised in [Location], he has been deeply committed to serving the people and advocating for meaningful change.\n\nKing holds a degree in [Field of Study] from [University Name] and has extensive experience in [related profession or public service]. Over the years, he has led numerous initiatives focused on [key achievements such as economic development, social welfare programs, education reforms, or infrastructure projects].\n\nAs a candidate for President, King Pacheco aims to prioritize good governance, economic growth, quality education, accessible healthcare, and national security. He believes in transparency, accountability, and inclusive leadership, ensuring that every citizen has a voice in shaping the nation's future.\n\nWith a strong track record of leadership, integrity, and dedication, King Pacheco is ready to lead the country toward progress and prosperity.\n\nCampaign Slogan: \"Together, We Build a Stronger Nation!\"",
                            CreatedAt = new DateTime(2025, 3, 14, 6, 46, 58, 0, DateTimeKind.Unspecified),
                            ElectionId = 10,
                            PartyId = 13,
                            PositionId = 8,
                            VoterId = 23
                        },
                        new
                        {
                            CandidateId = 12,
                            Biography = "q",
                            CreatedAt = new DateTime(2025, 3, 15, 3, 0, 59, 0, DateTimeKind.Unspecified),
                            ElectionId = 10,
                            PartyId = 5,
                            PositionId = 9,
                            VoterId = 24
                        },
                        new
                        {
                            CandidateId = 13,
                            Biography = "w",
                            CreatedAt = new DateTime(2025, 3, 15, 3, 1, 20, 0, DateTimeKind.Unspecified),
                            ElectionId = 10,
                            PartyId = 5,
                            PositionId = 10,
                            VoterId = 25
                        });
                });

            modelBuilder.Entity("eElection.Models.Election", b =>
                {
                    b.Property<int>("ElectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElectionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ElectionTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ElectionId");

                    b.ToTable("Elections");

                    b.HasData(
                        new
                        {
                            ElectionId = 10,
                            CreatedAt = new DateTime(2025, 3, 14, 0, 40, 44, 0, DateTimeKind.Unspecified),
                            ElectionName = "2025 National Election",
                            ElectionTypes = "National Elections",
                            EndDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            ElectionId = 11,
                            CreatedAt = new DateTime(2025, 3, 14, 0, 41, 13, 0, DateTimeKind.Unspecified),
                            ElectionName = "2025 Midterm Election",
                            ElectionTypes = "Midterm Elections",
                            EndDate = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            ElectionId = 13,
                            CreatedAt = new DateTime(2025, 3, 14, 7, 59, 5, 0, DateTimeKind.Unspecified),
                            ElectionName = "dsad",
                            ElectionTypes = "Midterm Elections,Regional Elections",
                            EndDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("eElection.Models.ElectionType", b =>
                {
                    b.Property<int>("ElectionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElectionTypeId"));

                    b.Property<int?>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("ElectionTypeName")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("ElectionTypeId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("PositionId");

                    b.ToTable("ElectionTypes");
                });

            modelBuilder.Entity("eElection.Models.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Leader")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            PartyId = 1,
                            CreatedAt = new DateTime(2025, 3, 6, 2, 1, 29, 0, DateTimeKind.Unspecified),
                            FoundedYear = 2001,
                            Leader = "Manny Villar",
                            PartyName = "NP"
                        },
                        new
                        {
                            PartyId = 2,
                            CreatedAt = new DateTime(2025, 3, 6, 2, 1, 54, 0, DateTimeKind.Unspecified),
                            FoundedYear = 2018,
                            Leader = "Bongbong Marcos",
                            PartyName = "PFP"
                        },
                        new
                        {
                            PartyId = 4,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1982,
                            Leader = "Aquilino \"Koko\" Pimentel III",
                            PartyName = "PDP–Laban"
                        },
                        new
                        {
                            PartyId = 5,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1907,
                            Leader = "Manny Villar",
                            PartyName = "Nacionalista Party"
                        },
                        new
                        {
                            PartyId = 6,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1946,
                            Leader = "Francis Pangilinan",
                            PartyName = "Liberal Party"
                        },
                        new
                        {
                            PartyId = 7,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1992,
                            Leader = "Lito Lapid",
                            PartyName = "Nationalist People’s Coalition"
                        },
                        new
                        {
                            PartyId = 8,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1991,
                            Leader = "Gloria Macapagal Arroyo",
                            PartyName = "Lakas–CMD"
                        },
                        new
                        {
                            PartyId = 9,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 2012,
                            Leader = "Jejomar Binay",
                            PartyName = "United Nationalist Alliance (UNA)"
                        },
                        new
                        {
                            PartyId = 10,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1997,
                            Leader = "Ernest Ramel",
                            PartyName = "Aksyon Demokratiko"
                        },
                        new
                        {
                            PartyId = 11,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 2009,
                            Leader = "Richard Gordon",
                            PartyName = "Bagumbayan-VNP"
                        },
                        new
                        {
                            PartyId = 12,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 2018,
                            Leader = "Ferdinand Marcos Jr.",
                            PartyName = "Partido Federal ng Pilipinas"
                        },
                        new
                        {
                            PartyId = 13,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1991,
                            Leader = "Miriam Defensor Santiago (deceased)",
                            PartyName = "People’s Reform Party"
                        },
                        new
                        {
                            PartyId = 14,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 2009,
                            Leader = "Neri Colmenares",
                            PartyName = "Makabayan Bloc"
                        },
                        new
                        {
                            PartyId = 15,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 32, 48, 0, DateTimeKind.Unspecified),
                            FoundedYear = 1991,
                            Leader = "Joseph Estrada",
                            PartyName = "Partido ng Masang Pilipino (PMP)"
                        });
                });

            modelBuilder.Entity("eElection.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 6,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "President"
                        },
                        new
                        {
                            PositionId = 7,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Vice President"
                        },
                        new
                        {
                            PositionId = 8,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Senators"
                        },
                        new
                        {
                            PositionId = 9,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "District Representatives"
                        },
                        new
                        {
                            PositionId = 10,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Party-List Representatives"
                        },
                        new
                        {
                            PositionId = 11,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Regional Governor"
                        },
                        new
                        {
                            PositionId = 12,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Regional Vice Governor"
                        },
                        new
                        {
                            PositionId = 13,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Regional Assembly Members"
                        },
                        new
                        {
                            PositionId = 14,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Governor"
                        },
                        new
                        {
                            PositionId = 15,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Vice Governor"
                        },
                        new
                        {
                            PositionId = 16,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Sangguniang Panlalawigan Members"
                        },
                        new
                        {
                            PositionId = 17,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "City/Municipal Mayor"
                        },
                        new
                        {
                            PositionId = 18,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "City/Municipal Vice Mayor"
                        },
                        new
                        {
                            PositionId = 19,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Sangguniang Panlungsod/Bayan Members"
                        },
                        new
                        {
                            PositionId = 20,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Barangay Captain (Punong Barangay)"
                        },
                        new
                        {
                            PositionId = 21,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Sangguniang Barangay Members"
                        },
                        new
                        {
                            PositionId = 22,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Sangguniang Kabataan (SK) Chairman"
                        },
                        new
                        {
                            PositionId = 23,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Sangguniang Kabataan (SK) Members"
                        },
                        new
                        {
                            PositionId = 24,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Councilors for Indigenous Peoples (IPs)"
                        },
                        new
                        {
                            PositionId = 25,
                            CreatedAt = new DateTime(2025, 3, 15, 2, 38, 39, 0, DateTimeKind.Unspecified),
                            PositionName = "Councilors for Sectoral Representatives"
                        });
                });

            modelBuilder.Entity("eElection.Models.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("VoterId")
                        .HasColumnType("int");

                    b.HasKey("VoteId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("eElection.Models.VoteDetail", b =>
                {
                    b.Property<int>("VoteDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteDetailId"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int>("VoteId")
                        .HasColumnType("int");

                    b.HasKey("VoteDetailId");

                    b.HasIndex("VoteId");

                    b.ToTable("VoteDetails");
                });

            modelBuilder.Entity("eElection.Models.Voter", b =>
                {
                    b.Property<int>("VoterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoterId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoterId");

                    b.ToTable("Voters");

                    b.HasData(
                        new
                        {
                            VoterId = 4,
                            Address = "",
                            Birthdate = new DateOnly(1, 1, 1),
                            CreatedAt = new DateTime(2025, 3, 8, 3, 49, 49, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "",
                            Gender = "",
                            LastName = "",
                            Phone = "",
                            ProfilePhoto = "",
                            Status = ""
                        },
                        new
                        {
                            VoterId = 6,
                            Address = "Parang",
                            Birthdate = new DateOnly(1, 1, 1),
                            CreatedAt = new DateTime(2025, 3, 10, 7, 33, 19, 0, DateTimeKind.Unspecified),
                            Email = "lemuelcueto21@gmail.com",
                            FirstName = "John Lemuel",
                            Gender = "",
                            LastName = "Cueto",
                            Phone = "09123456789",
                            ProfilePhoto = "",
                            Status = ""
                        },
                        new
                        {
                            VoterId = 22,
                            Address = "Tibag",
                            Birthdate = new DateOnly(2025, 3, 21),
                            CreatedAt = new DateTime(2025, 3, 14, 0, 58, 0, 0, DateTimeKind.Unspecified),
                            Email = "cueto.johnlemuel.j@gmail.com",
                            FirstName = "Jandel",
                            Gender = "Male",
                            LastName = "Escaleraa",
                            Phone = "09123456789",
                            ProfilePhoto = "",
                            Status = "Pending"
                        },
                        new
                        {
                            VoterId = 23,
                            Address = "Lazareto",
                            Birthdate = new DateOnly(2025, 3, 14),
                            CreatedAt = new DateTime(2025, 3, 14, 0, 59, 44, 0, DateTimeKind.Unspecified),
                            Email = "johnlemuelcueto.olloka@gmail.com",
                            FirstName = "King",
                            Gender = "Male",
                            LastName = "Pacheco",
                            Phone = "09123456789",
                            ProfilePhoto = "",
                            Status = "Pending"
                        },
                        new
                        {
                            VoterId = 24,
                            Address = "Victoria",
                            Birthdate = new DateOnly(2025, 3, 15),
                            CreatedAt = new DateTime(2025, 3, 15, 2, 53, 19, 0, DateTimeKind.Unspecified),
                            Email = "deployhaha@gmail.com",
                            FirstName = "Quinee",
                            Gender = "Female",
                            LastName = "Deguzman",
                            Phone = "09123456789",
                            ProfilePhoto = "",
                            Status = "Pending"
                        },
                        new
                        {
                            VoterId = 25,
                            Address = "Xevera",
                            Birthdate = new DateOnly(2025, 3, 15),
                            CreatedAt = new DateTime(2025, 3, 15, 2, 54, 58, 0, DateTimeKind.Unspecified),
                            Email = "jandeleido@gmail.com",
                            FirstName = "Jean Claude",
                            Gender = "Male",
                            LastName = "Manalo",
                            Phone = "09123456789",
                            ProfilePhoto = "",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("eElection.Models.Account", b =>
                {
                    b.HasOne("eElection.Models.Voter", "Voter")
                        .WithOne("Account")
                        .HasForeignKey("eElection.Models.Account", "VoterId");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("eElection.Models.Candidate", b =>
                {
                    b.HasOne("eElection.Models.Election", "Election")
                        .WithMany("Candidates")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eElection.Models.Party", "Party")
                        .WithMany("Candidates")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eElection.Models.Position", "Position")
                        .WithMany("Candidates")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eElection.Models.Voter", "Voter")
                        .WithMany("Candidates")
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("Party");

                    b.Navigation("Position");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("eElection.Models.ElectionType", b =>
                {
                    b.HasOne("eElection.Models.Election", null)
                        .WithMany("ElectionTypePositions")
                        .HasForeignKey("ElectionId");

                    b.HasOne("eElection.Models.Position", "Position")
                        .WithMany("ElectionTypes")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("eElection.Models.VoteDetail", b =>
                {
                    b.HasOne("eElection.Models.Vote", "Vote")
                        .WithMany()
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("eElection.Models.Election", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("ElectionTypePositions");
                });

            modelBuilder.Entity("eElection.Models.Party", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("eElection.Models.Position", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("ElectionTypes");
                });

            modelBuilder.Entity("eElection.Models.Voter", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
